---
- name: run zabbix agents
  hosts: haproxy, web
  tasks:
    - name: run zabbix agent on haproxy vm
      shell: |
        systemctl start docker
        docker pull zabbix/zabbix-agent
        docker run --name zabbix-agent --privileged -e ZBX_SERVER_HOST={{ zabbix_server }} -d -p 10050:10050 zabbix/zabbix-agent:latest